version: '2.1'

volumes:
    adguardhome_work:
    adguardhome_conf:

services:

    adguard:
        image: adguard/adguardhome:v0.106.3
        network_mode: host
        privileged: true
        volumes:
            - 'adguardhome_work:/opt/adguardhome/work:rw'
            - 'adguardhome_conf:/opt/adguardhome/conf:rw'
        command: --host 0.0.0.0 --port 80 --no-check-update --config /opt/adguardhome/conf/AdGuardHome.yaml

    rpiplay:
        build: air-pi-play/
        privileged: true
        restart: always
        network_mode: host
        devices:
          - /dev/dri
          - /dev/vchiq
        group_add:
          - video
          - audio
        environment: 
            - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
        labels:
            io.balena.features.dbus: '1'

